config/routes.rb
Rails.application.routes.draw do


  resources :audit_logs
  resources :company_banks
  resources :admin_watchdogs
  resources :admin_logins
  resources :selfie_verifications,:except => [:new, :create]
  resources :address_verifications,:except => [:new, :create]
  resources :nationalid_verifications,:except => [:new, :create]
  resources :user_infos
  resources :user_verifications
  resources :user_verfications
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :watchdogs
      resources :users
      resources :countries
      resources :affilate_programs
      post "users/create" => "users#create"
      get "homepage" => "users#homepage"
      post "confirmmail" => "users#confirmmail"
      post "resend_confirmmail" => "users#resend_confirmmail"
      get "two_factor" => "users#get_two_factor"
      post "two_factor" => "users#post_two_factor"
      get "statistics" => "users#statistics"
      get "lock_unlock_account" => "users#lock_unlock_account"
      get "send_confirmation_email" => "users#send_confirmation_email"
      get "change_confirmation_code" => "users#change_confirmation_code"
      get "confirm_google_code" => "users#confirm_google_code"
      get "set_otp_code" => "users#set_otp_code"
      get "user_log" => "watchdogs#user_log"
      get "active_sessions" => "logins#active_sessions"
      post 'auth_user' => 'authentication#authenticate_user'
      post "unlockaccount" => "authentication#unlockaccount"
      post "send_invitation_email" => "affilate_programs#send_invitation_email"
      post 'getEditToken' => 'authentication#getEditToken'
      resources :cards_logs
      resources :cards_categories
      resources :cards
      get "search" => "cards#search"
      post "search" => "cards#searchpost"
      get "buy_card" => "cards#buy_card" 
      get "cards_status" => "cards#cards_status"
      get "display_cards_categories" => "cards_categories#display_cards_categories"
      resources :addresses
      get "search_address" => "addresses#search"
      post "search_address" => "addresses#searchpost"
      get "delete_user_addresses" => "addresses#delete_user_addresses"
      get "user_addresses" => "addresses#user_addresses"
      get "send_sms" => "user_wallets#send_sms"
      post "send_sms_post" => "user_wallets#send_sms_post"
      post "verifysms_post" => "user_wallets#verifysms_post"
      get "verifysms" => "user_wallets#verifysms"
      get "wallets_status" => "user_wallets#wallets_status"
      get "transfer_balance" => "user_wallets#transfer_balance"
      post "transfer_balance" => "user_wallets#transfer_balancepost"
      resources :wallets_transfer_ratios
      resources :user_wallets
      resources :sms_logs
      resources :notifications
      resources :notifications_settings
      get "user_notifications" => "notifications#user_notifications"
      get "search_notifications" => "notifications#search"
      get "add_defualt_notifications" => "notifications_settings#add_defualt_notifications"
      resources :uploads
      resources :money_ops
      get "operations_status" => "money_ops#operations_status"
      resources :bank_accounts
      resources :ticket_departments
      resources :tickets
      get 'tickets/:id/replies' => 'tickets#showreplies'
      post 'tickets/reply' => 'tickets#create_reply'
      resources :withdraws

    end
  end

  resources :withdraws
  resources :admins,:except => [:new]
  resources :affilate_programs
  resources :countries
  resources :logins
  resources :verifications
  resources :watchdogs
  resources :users,:except => [:new]
  root "admins#homepage"
  get "confirmmail" => "users#confirmmail"
  get "unlockaccount" => "admins#unlockaccount"
  get "two_factor" => "admins#get_two_factor"
  post "two_factor" => "admins#post_two_factor"
  get "user_log" => "watchdogs#user_log"
  get "audit_log" => "audit_logs#user_audit_log"
  get "admin_log" => "admin_watchdogs#admin_log"
  get "statistics" => "admins#statistics"
  get "lock_unlock_account" => "users#lock_unlock_account"
  get "active_sessions" => "logins#active_sessions"
  get "admin_active_sessions" => "admin_logins#admin_active_sessions"
  get "send_confirmation_email" => "admins#send_confirmation_email"
  get "change_confirmation_code" => "admins#change_confirmation_code"
  get "confirm_google_code" => "admins#confirm_google_code"
  #get "affilate-program/:refered_by" => "affilate_programs#send_invitation"
  #post "send_invitation_email" => "affilate_programs#send_invitation_email"
  #get "edit_password/:id" => "users#edit_password" , :as => "edit_password" 
  get "add_admin" => "admins#add_admin"
  post "add_admin" => "admins#add_admin_post"
  get "error_page" => "logins#error_page"
  get "lock_page" => "admin_logins#lock_page"
  post "lock_page" => "admin_logins#check_to_unlock"
  resources :cards_logs
  resources :cards_categories
  resources :cards
  get "search" => "cards#search"
  post "search" => "cards#searchpost"
  get "buy_card" => "cards#buy_card" 
  get "cards_status" => "cards#cards_status"
  get "display_cards_categories" => "cards_categories#display_cards_categories"
  resources :addresses
  get "search_address" => "addresses#search"
  post "search_address" => "addresses#searchpost"
  get "delete_user_addresses" => "addresses#delete_user_addresses"
  get "user_addresses" => "addresses#user_addresses"
  get "send_sms" => "user_wallets#send_sms"
  post "send_sms_post" => "user_wallets#send_sms_post"
  post "verifysms_post" => "user_wallets#verifysms_post"
  get "verifysms" => "user_wallets#verifysms"
  get "wallets_status" => "user_wallets#wallets_status"
  get "user_list_data" => "user_wallets#user_list_data"
  get "transfer_balance" => "user_wallets#transfer_balance"
  post "transfer_balance" => "user_wallets#transfer_balancepost"
  get "admin_add_balance" => "user_wallets#admin_add_balance"
  post "admin_add_balance_post" => "user_wallets#admin_add_balance_post"
  resources :wallets_transfer_ratios
  resources :user_wallets
  resources :users_wallets_transfers
  resources :sms_logs
  resources :notifications
  resources :notifications_settings
  get "user_notifications" => "notifications#user_notifications"
  get "search_notifications" => "notifications#search"
  get "add_defualt_notifications" => "notifications_settings#add_defualt_notifications"
  resources :uploads
  resources :money_ops
  get "operations_status" => "money_ops#operations_status"
  resources :bank_accounts
  resources :ticket_departments
  resources :tickets
  get 'tickets/:id/replies' => 'tickets#showreplies'
  post 'tickets/reply' => 'tickets#create_reply'
  get "user_bank_accounts" => "withdraws#user_bank_accounts"
  get "close_ticket" => "tickets#close_ticket"
  
  resources :passwords,
      controller: 'clearance/passwords',
      only: [:create, :new]

  resource :session,
      controller: 'clearance/sessions',
      only: [:create]

  resources :admins,
      controller: 'admins',
      only: Clearance.configuration.user_actions do
        resource :password,
          controller: 'clearance/passwords',
          only: [:create, :edit, :update]
      end

  get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
  delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'

  if Clearance.configuration.allow_sign_up?
   get '/sign_up' => 'admins#new', as: 'sign_up'
  end
  



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cards_category.rb
class CardsCategory < ApplicationRecord

    validates_uniqueness_of :card_value
    validates_uniqueness_of :order

end

app/controllers/api/v1/cards_categories_controller.rb
module Api
  module V1
    class CardsCategoriesController < ApplicationController
      before_action :set_cards_category, only: [:show, :edit, :update, :destroy]
      skip_before_action :verify_authenticity_token

      # GET /cards_categories
      def index

        @cards_categories = CardsCategory.all
        respond_to do |format|
          format.json { render json: @cards_categories }
        end

        # =begin
        # @api {get} /api/v1/cards_categories 1-Request cards categories List
        # @apiVersion 0.3.0
        # @apiName GetCardsCategories
        # @apiGroup Cards Categories
        # @apiExample Example usage:
        # curl -i http://localhost:3000/api/v1/cards_categories
        # @apiSuccess {Number} id category unique ID.
        # @apiSuccess {Number} card_value card category value.
        # @apiSuccess {Number} active control card category display(1 for display & 0 for hide).
        # @apiSuccess {Number} order category order(high order for high category value).
        # @apiSuccess {Date} created_at  Date created.
        # @apiSuccess {Date} updated_at  Date Updated.
        # @apiSuccessExample Success-Response:
        # HTTP/1.1 200 OK
        # [
        # {
        #     "id": 1,
        #     "card_value": 100,
        #     "active": 1,
        #     "order": 1,
        #     "created_at": "2018-07-26T14:41:50.506Z",
        #     "updated_at": "2018-07-28T08:03:16.400Z"
        # },
        # {
        #   "id": 3,
        #   "card_value": 300,
        #   "active": 0,
        #   "order": 3,
        #   "created_at": "2018-07-26T14:49:06.665Z",
        #   "updated_at": "2018-07-28T08:38:59.747Z"
        # }
        # ]
        # @apiError MissingToken invalid Token.
        # @apiErrorExample Error-Response:
        # HTTP/1.1 400 Bad Request
        #   {
        #     "error": "Missing token"
        #   }
        # =end

      end

      # GET /cards_categories/1
      # GET /cards_categories/1.json
      def show

        respond_to do |format|
          format.json { render json: @cards_category }
        end
        
        # =begin
        # @api {get} /api/v1/cards_categories/{:id} 3-Request Specific card category
        # @apiVersion 0.3.0
        # @apiName GetSpecificCardsCategories
        # @apiGroup Cards Categories
        # @apiExample Example usage:
        # curl -i http://localhost:3000/api/v1/cards_categories/3
        # @apiParam {Number} id Card Category unique ID.
        # @apiSuccess {Number} card_value card category value.
        # @apiSuccess {Number} active control card category display(1 for display & 0 for hide).
        # @apiSuccess {Number} order category order(high order for high category value).
        # @apiSuccess {Date} created_at  Date created.
        # @apiSuccess {Date} updated_at  Date Updated.
        # @apiSuccessExample Success-Response:
        # HTTP/1.1 200 OK
        # {
        #   "id": 3,
        #   "card_value": 300,
        #   "active": 0,
        #   "order": 3,
        #   "created_at": "2018-07-26T14:49:06.665Z",
        #   "updated_at": "2018-07-28T08:38:59.747Z"
        # }
        # @apiError MissingToken invalid Token.
        # @apiErrorExample Error-Response:
        # HTTP/1.1 400 Bad Request
        #   {
        #     "error": "Missing token"
        #   }
        # @apiError CategoryNotFound The id of the Card Category was not found. 
        # @apiErrorExample Error-Response:
        # HTTP/1.1 404 Not Found
        #   {
        #     "error": "CategoryNotFound"
        #   }
        # =end

      end

      def display_cards_categories

        @categories = CardsCategory.where(:active => 1).all.order(card_value: :desc)
        respond_to do |format|
          format.json { render json: @categories }
        end

        # =begin
        # @api {get} /api/v1/display_cards_categories 2-Request displayed cards categories List
        # @apiVersion 0.3.0
        # @apiName GetDisplayedCardsCategories
        # @apiGroup Cards Categories
        # @apiExample Example usage:
        # curl -i http://localhost:3000/api/v1/display_cards_categories
        # @apiSuccess {Number} id category unique ID.
        # @apiSuccess {Number} card_value card category value.
        # @apiSuccess {Number} active control card category display(1 for display & 0 for hide).
        # @apiSuccess {Number} order category order(high order for high category value).
        # @apiSuccess {Date} created_at  Date created.
        # @apiSuccess {Date} updated_at  Date Updated.
        # @apiSuccessExample Success-Response:
        # HTTP/1.1 200 OK
        # [
        # {
        #     "id": 1,
        #     "card_value": 100,
        #     "active": 1,
        #     "order": 1,
        #     "created_at": "2018-07-26T14:41:50.506Z",
        #     "updated_at": "2018-07-28T08:03:16.400Z"
        # },
        # {
        #     "id": 2,
        #     "card_value": 200,
        #     "active": 1,
        #     "order": 2,
        #     "created_at": "2018-07-26T14:48:50.514Z",
        #     "updated_at": "2018-07-28T08:38:53.795Z"
        # }
        # ]
        # @apiError MissingToken invalid Token.
        # @apiErrorExample Error-Response:
        # HTTP/1.1 400 Bad Request
        #   {
        #     "error": "Missing token"
        #   }
        # =end

      end

      # GET /cards_categories/new
      def new
        @cards_category = CardsCategory.new
      end

      # GET /cards_categories/1/edit
      def edit
      end

      # POST /cards_categories
      def create
        @cards_category = CardsCategory.new(cards_category_params)

        respond_to do |format|
          if @cards_category.save
            format.json { render json: @cards_category, status: :created, location: @cards_category }
          else
            format.json { render json: @cards_category.errors, status: :unprocessable_entity }
          end
        end

        # =begin
        # @api {post} /api/v1/cards_categories 4-Create a new Card Category
        # @apiVersion 0.3.0
        # @apiName PostCardCategory
        # @apiGroup Cards Categories
        # @apiExample Example usage:
        # curl -X POST \
        # http://localhost:3000/api/v1/cards_categories \
        # -H 'cache-control: no-cache' \
        # -H 'content-type: application/json' \
        # -d '{
        #   "card_value": 500,
        #   "active": 1,
        #   "order": 5,
        # }'
        # @apiParam {Number} card_value card category value.
        # @apiParam {Number} active control card category display(1 for display & 0 for hide).
        # @apiParam {Number} order category unique order(high order for high category value).
        # @apiSuccess {Number} id category unique ID.
        # @apiSuccess {Number} card_value card category value.
        # @apiSuccess {Number} active control card category display(1 for display & 0 for hide).
        # @apiSuccess {Number} order category order(high order for high category value).
        # @apiSuccess {Date} created_at  Date created.
        # @apiSuccess {Date} updated_at  Date Updated.
        # @apiSuccessExample Success-Response:
        # HTTP/1.1 200 OK
        # {
        #   "id": 5,
        #   "card_value": 500,
        #   "active": 0,
        #   "order": 5,
        #   "created_at": "2018-07-28T12:37:11.483Z",
        #   "updated_at": "2018-07-28T12:37:11.483Z"
        # }
        # @apiError MissingToken missing user name or password.
        # @apiErrorExample Error-Response1:
        # HTTP/1.1 422 Missing token
        #   {
        #     "error": "Missing token"
        #   }
        # @apiError ExistingValue card category value has already been taken.
        # @apiErrorExample Error-Response2:
        # HTTP/1.1 Existing Category Value
        #   {
        #     "error": "has already been taken"
        #   }
        # @apiError ExistingOrder card category order has already been taken.
        # @apiErrorExample Error-Response3:
        # HTTP/1.1 Invalid Order
        #   {
        #     "error": "has already been taken"
        #   }
        # =end
      end

      # PATCH/PUT /cards_categories/id
      def update

        respond_to do |format|
          if @cards_category.update(card_params)
            format.json { render json: @cards_category, status: :ok, location: @cards_category }
          else
            format.json { render json: @cards_category.errors, status: :unprocessable_entity }
          end
        end

        # =begin
        # @api {post} /api/v1/cards_categories/{:id} 5-Update an existing Card Category
        # @apiVersion 0.3.0
        # @apiName PutCardCategory
        # @apiGroup Cards Categories
        # @apiExample Example usage:
        # curl -X PUT \
        # http://localhost:3000/api/v1/cards_categories/5 \
        # -H 'cache-control: no-cache' \
        # -H 'content-type: application/json' \
        # -d '{
        #   "card_value": 400,
        #   "active": 1,
        #   "order": 5,
        # }'
        # @apiParam {Number} card_value card category value.
        # @apiParam {Number} active control card category display(1 for display & 0 for hide).
        # @apiParam {Number} order category unique order(high order for high category value).
        # @apiSuccess {Number} id category unique ID.
        # @apiSuccess {Number} card_value card category value.
        # @apiSuccess {Number} active control card category display(1 for display & 0 for hide).
        # @apiSuccess {Number} order category order(high order for high category value).
        # @apiSuccess {Date} created_at  Date created.
        # @apiSuccess {Date} updated_at  Date Updated.
        # @apiSuccessExample Success-Response:
        # HTTP/1.1 200 OK
        # {
        #   "id": 5,
        #   "card_value": 400,
        #   "active": 1,
        #   "order": 5,
        #   "created_at": "2018-07-28T12:37:11.483Z",
        #   "updated_at": "2018-07-28T15:24:10.303Z"

app/helpers/cards_categories_helper.rb
module CardsCategoriesHelper
end

app/views/cards_categories/_form.html.erb
<%= form_with(model: cards_category, local: true) do |form| %>
  <% if cards_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cards_category.errors.count, "error") %> prohibited this cards_category from being saved:</h2>

      <ul>
      <% cards_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :card_value %>
    <%= form.number_field :card_value %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.select :active,options_for_select([['display',1],['hide',0]]),  {}, {} %>
  </div>

  <div class="field">
    <%= form.label :order %>
    <%= form.select :order, ((1..20).map {|i| [i,i] }), {:include_blank => 'select order'} %>
    <%# form.number_field :order %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cards_categories/display_cards_categories.html.erb
<!DOCTYPE html>
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
</head>
<body>
 
<div class="container">
<h1>Displayed Cards Categories</h1>
<div class="row">
  <div class="card" style="width:300px">
    <div class="card-body">
      <h4 class="card-title"><%= @categories[0].card_value %></h4> 
      <a href="/cards_categories/<%= @categories[0].id %>" class="btn btn-primary">Show</a>
      <a href="/buy_card?val=<%= @categories[0].card_value%>" style="float: right;" class="btn btn-primary">Buy Card</a>
    </div>
  </div>
  
  <div class="card" style="width:300px">
    <div class="card-body">
      <h4 class="card-title"><%= @categories[1].card_value %></h4>
      <a href="/cards_categories/<%= @categories[1].id %>" class="btn btn-primary">Show</a>
      <a href="/buy_card?val=<%= @categories[1].card_value%>" style="float: right;" class="btn btn-primary">Buy Card</a>
    </div>
  </div>
</div>
<br>
<div class="row">
  <div class="card" style="width:300px">
    <div class="card-body">
      <h4 class="card-title"><%= @categories[2].card_value %></h4> 
      <a href="/cards_categories/<%= @categories[2].id %>" class="btn btn-primary">Show</a>
      <a href="/buy_card?val=<%= @categories[2].card_value%>" style="float: right;" class="btn btn-primary">Buy Card</a>
    </div>
  </div>
  
  <div class="card" style="width:300px">
    <div class="card-body">
      <h4 class="card-title"><%= @categories[3].card_value %></h4>
      <a href="/cards_categories/<%= @categories[3].id %>" class="btn btn-primary">Show</a>
      <a href="/buy_card?val=<%= @categories[3].card_value%>" style="float: right;" class="btn btn-primary">Buy Card</a>
    </div>
  </div>
</div>
</div>
<br>

<%= link_to 'New Cards Category', new_cards_category_path %><br>
<%= link_to 'Cards Category', cards_categories_path %>

</body>

app/views/cards_categories/edit.html.erb
<h1>Editing Cards Category</h1>

<%= form_with(model: @cards_category, local: true) do |form| %>
    <% if @cards_category.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@cards_category.errors.count, "error") %> prohibited this cards_category from being saved:</h2>
  
        <ul>
        <% @cards_category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :card_value %>
      <%= form.number_field :card_value %>
    </div>
  
    <div class="field">
      <%= form.label :active %>
      <%= form.select :active,options_for_select([['display',1],['hide',0]], :selected => @cards_category.active),  {}, {} %>
    </div>
  
    <div class="field">
      <%= form.label :order %>
      <%= form.select :order, ((1..20).map {|i| [i,i] }), {:include_blank => 'select order'} %>
      <%# form.number_field :order %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  

<%= link_to 'Show', @cards_category %> |
<%= link_to 'Back', cards_categories_path %>

app/views/cards_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cards Categories</h1>

<table>
  <thead>
    <tr>
      <th>Card value</th>
      <th>Active</th>
      <th>Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards_categories.each do |cards_category| %>
      <tr>
        <td><%= cards_category.card_value %></td>
        <% if cards_category.active == 1 %>
        <td><%= "Display" %></td>
        <% elsif cards_category.active == 0 %>
        <td><%= "Hide" %></td>
        <% end %>
        <td><%= cards_category.order %></td>
        <td><%= link_to 'Show', cards_category %></td>
        <td><%= link_to 'Edit', edit_cards_category_path(cards_category) %></td>
        <td><%= link_to 'Destroy', cards_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cards Category', new_cards_category_path %> <br><br>

app/views/cards_categories/new.html.erb
<h1>New Cards Category</h1>

<%= render 'form', cards_category: @cards_category %>

<%= link_to 'Back', cards_categories_path %>

app/views/cards_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Card value:</strong>
  <%= @cards_category.card_value %>
</p>

<p>
  <strong>Active:</strong>
  <%= @cards_category.active %>
</p>

<p>
  <strong>Order:</strong>
  <%= @cards_category.order %>
</p>

<%= link_to 'Edit', edit_cards_category_path(@cards_category) %> |
<%= link_to 'Back', cards_categories_path %>