config/routes.rb
Rails.application.routes.draw do


  resources :audit_logs
  resources :company_banks
  resources :admin_watchdogs
  resources :admin_logins
  resources :selfie_verifications,:except => [:new, :create]
  resources :address_verifications,:except => [:new, :create]
  resources :nationalid_verifications,:except => [:new, :create]
  resources :user_infos
  resources :user_verifications
  resources :user_verfications
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :watchdogs
      resources :users
      resources :countries
      resources :affilate_programs
      post "users/create" => "users#create"
      get "homepage" => "users#homepage"
      post "confirmmail" => "users#confirmmail"
      post "resend_confirmmail" => "users#resend_confirmmail"
      get "two_factor" => "users#get_two_factor"
      post "two_factor" => "users#post_two_factor"
      get "statistics" => "users#statistics"
      get "lock_unlock_account" => "users#lock_unlock_account"
      get "send_confirmation_email" => "users#send_confirmation_email"
      get "change_confirmation_code" => "users#change_confirmation_code"
      get "confirm_google_code" => "users#confirm_google_code"
      get "set_otp_code" => "users#set_otp_code"
      get "user_log" => "watchdogs#user_log"
      get "active_sessions" => "logins#active_sessions"
      post 'auth_user' => 'authentication#authenticate_user'
      post "unlockaccount" => "authentication#unlockaccount"
      post "send_invitation_email" => "affilate_programs#send_invitation_email"
      post 'getEditToken' => 'authentication#getEditToken'
      resources :cards_logs
      resources :cards_categories
      resources :cards
      get "search" => "cards#search"
      post "search" => "cards#searchpost"
      get "buy_card" => "cards#buy_card" 
      get "cards_status" => "cards#cards_status"
      get "display_cards_categories" => "cards_categories#display_cards_categories"
      resources :addresses
      get "search_address" => "addresses#search"
      post "search_address" => "addresses#searchpost"
      get "delete_user_addresses" => "addresses#delete_user_addresses"
      get "user_addresses" => "addresses#user_addresses"
      get "send_sms" => "user_wallets#send_sms"
      post "send_sms_post" => "user_wallets#send_sms_post"
      post "verifysms_post" => "user_wallets#verifysms_post"
      get "verifysms" => "user_wallets#verifysms"
      get "wallets_status" => "user_wallets#wallets_status"
      get "transfer_balance" => "user_wallets#transfer_balance"
      post "transfer_balance" => "user_wallets#transfer_balancepost"
      resources :wallets_transfer_ratios
      resources :user_wallets
      resources :sms_logs
      resources :notifications
      resources :notifications_settings
      get "user_notifications" => "notifications#user_notifications"
      get "search_notifications" => "notifications#search"
      get "add_defualt_notifications" => "notifications_settings#add_defualt_notifications"
      resources :uploads
      resources :money_ops
      get "operations_status" => "money_ops#operations_status"
      resources :bank_accounts
      resources :ticket_departments
      resources :tickets
      get 'tickets/:id/replies' => 'tickets#showreplies'
      post 'tickets/reply' => 'tickets#create_reply'
      resources :withdraws

    end
  end

  resources :withdraws
  resources :admins,:except => [:new]
  resources :affilate_programs
  resources :countries
  resources :logins
  resources :verifications
  resources :watchdogs
  resources :users,:except => [:new]
  root "admins#homepage"
  get "confirmmail" => "users#confirmmail"
  get "unlockaccount" => "admins#unlockaccount"
  get "two_factor" => "admins#get_two_factor"
  post "two_factor" => "admins#post_two_factor"
  get "user_log" => "watchdogs#user_log"
  get "audit_log" => "audit_logs#user_audit_log"
  get "admin_log" => "admin_watchdogs#admin_log"
  get "statistics" => "admins#statistics"
  get "lock_unlock_account" => "users#lock_unlock_account"
  get "active_sessions" => "logins#active_sessions"
  get "admin_active_sessions" => "admin_logins#admin_active_sessions"
  get "send_confirmation_email" => "admins#send_confirmation_email"
  get "change_confirmation_code" => "admins#change_confirmation_code"
  get "confirm_google_code" => "admins#confirm_google_code"
  #get "affilate-program/:refered_by" => "affilate_programs#send_invitation"
  #post "send_invitation_email" => "affilate_programs#send_invitation_email"
  #get "edit_password/:id" => "users#edit_password" , :as => "edit_password" 
  get "add_admin" => "admins#add_admin"
  post "add_admin" => "admins#add_admin_post"
  get "error_page" => "logins#error_page"
  get "lock_page" => "admin_logins#lock_page"
  post "lock_page" => "admin_logins#check_to_unlock"
  resources :cards_logs
  resources :cards_categories
  resources :cards
  get "search" => "cards#search"
  post "search" => "cards#searchpost"
  get "buy_card" => "cards#buy_card" 
  get "cards_status" => "cards#cards_status"
  get "display_cards_categories" => "cards_categories#display_cards_categories"
  resources :addresses
  get "search_address" => "addresses#search"
  post "search_address" => "addresses#searchpost"
  get "delete_user_addresses" => "addresses#delete_user_addresses"
  get "user_addresses" => "addresses#user_addresses"
  get "send_sms" => "user_wallets#send_sms"
  post "send_sms_post" => "user_wallets#send_sms_post"
  post "verifysms_post" => "user_wallets#verifysms_post"
  get "verifysms" => "user_wallets#verifysms"
  get "wallets_status" => "user_wallets#wallets_status"
  get "user_list_data" => "user_wallets#user_list_data"
  get "transfer_balance" => "user_wallets#transfer_balance"
  post "transfer_balance" => "user_wallets#transfer_balancepost"
  get "admin_add_balance" => "user_wallets#admin_add_balance"
  post "admin_add_balance_post" => "user_wallets#admin_add_balance_post"
  resources :wallets_transfer_ratios
  resources :user_wallets
  resources :users_wallets_transfers
  resources :sms_logs
  resources :notifications
  resources :notifications_settings
  get "user_notifications" => "notifications#user_notifications"
  get "search_notifications" => "notifications#search"
  get "add_defualt_notifications" => "notifications_settings#add_defualt_notifications"
  resources :uploads
  resources :money_ops
  get "operations_status" => "money_ops#operations_status"
  resources :bank_accounts
  resources :ticket_departments
  resources :tickets
  get 'tickets/:id/replies' => 'tickets#showreplies'
  post 'tickets/reply' => 'tickets#create_reply'
  get "user_bank_accounts" => "withdraws#user_bank_accounts"
  get "close_ticket" => "tickets#close_ticket"
  
  resources :passwords,
      controller: 'clearance/passwords',
      only: [:create, :new]

  resource :session,
      controller: 'clearance/sessions',
      only: [:create]

  resources :admins,
      controller: 'admins',
      only: Clearance.configuration.user_actions do
        resource :password,
          controller: 'clearance/passwords',
          only: [:create, :edit, :update]
      end

  get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
  delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'

  if Clearance.configuration.allow_sign_up?
   get '/sign_up' => 'admins#new', as: 'sign_up'
  end
  



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/api/v1/cards_controller.rb
module Api
  module V1
    class CardsController < ApplicationController
       before_action :set_card, only: [:show, :edit, :update, :destroy]
       skip_before_action :verify_authenticity_token

      # GET /cards
      def index
        @cards = Card.all
        respond_to do |format|
          format.json { render json: @cards }
        end

      # =begin
      # @api {get} /api/v1/cards 1-Request cards List
      # @apiVersion 0.3.0
      # @apiName GetCard
      # @apiGroup Cards
      # @apiExample Example usage:
      # curl -i http://localhost:3000/api/v1/cards
      # @apiSuccess {Number} id card unique ID.
      # @apiSuccess {Number} number card unique number.
      # @apiSuccess {Number} value card value.
      # @apiSuccess {Number} status card status.
      # @apiSuccess {Date} expired_at  card expired Date.
      # @apiSuccess {Number} invoice_id card invoice ID.
      # @apiSuccess {Date} created_at  Date created.
      # @apiSuccess {Date} updated_at  Date Updated.
      # @apiSuccessExample Success-Response:
      # HTTP/1.1 200 OK
      # [
      #      {
      #         "id": 5,
      #         "number": 1234567891234566,
      #         "value": 150,
      #         "status": 3,
      #         "expired_at": "2018-07-24",
      #         "user_id": 2,
      #         "invoice_id": 0,
      #         "created_at": "2018-07-24T12:50:56.749Z",
      #         "updated_at": "2018-07-24T12:51:18.567Z"
      #     },
      #     {
      #         "id": 6,
      #         "number": 5722704937640978,
      #         "value": 200,
      #         "status": 1,
      #         "expired_at": "2022-06-25",
      #         "user_id": 1,
      #         "invoice_id": 0,
      #         "created_at": "2018-07-24T13:24:23.665Z",
      #         "updated_at": "2018-07-24T13:24:23.665Z"
      #     }
      # ]
      # @apiError MissingToken invalid Token.
      # @apiErrorExample Error-Response:
      # HTTP/1.1 400 Bad Request
      #   {
      #     "error": "Missing token"
      #   }
      # =end
      end

      # GET /cards/:id
      def show
        # =begin
        # @api {get} /api/v1/cards/{:id} 2-Request Specific Card
        # @apiVersion 0.3.0
        # @apiName GetSpecificCard
        # @apiGroup Cards
        # @apiExample Example usage:
        # curl -i http://localhost:3000/api/v1/cards/1
        # @apiParam {Number} id Card ID.
        # @apiSuccess {Number} id card unique ID.
        # @apiSuccess {Number} number card unique number.
        # @apiSuccess {Number} value card value.
        # @apiSuccess {Number} status card status.
        # @apiSuccess {Date} expired_at  card expired Date.
        # @apiSuccess {Number} invoice_id card invoice ID.
        # @apiSuccess {Date} created_at  Date created.
        # @apiSuccess {Date} updated_at  Date Updated.
        # @apiSuccessExample Success-Response:
        # HTTP/1.1 200 OK
        #     {
        #         "id": 1,
        #         "number": 5722702457640936,
        #         "value": 100,
        #         "status": 2,
        #         "expired_at": "2022-05-20",
        #         "user_id": 1,
        #         "invoice_id": 0,
        #         "created_at": "2018-07-24T13:24:23.665Z",
        #         "updated_at": "2018-07-24T13:24:23.665Z"
        #     }
        # @apiError CardNotFound The id of the Card was not found. 
        # @apiErrorExample Error-Response1:
        # HTTP/1.1 404 Not Found
        #   {
        #     "error": "CardNotFound"
        #   }
        # @apiError MissingToken invalid token.
        # @apiErrorExample Error-Response2:
        # HTTP/1.1 400 Bad Request
        #   {
        #     "error": "Missing token"
        #   }
        # =end

        respond_to do |format|
          format.json { render json: @card }
        end

      end

      # GET /cards/new
      def new
        @card = Card.new
      end

      # GET /cards/:id/edit
      def edit
      end

      # POST /cards
      def create

        # =begin
        # @api {post} /api/v1/cards 3-Create a new Card
        # @apiVersion 0.3.0
        # @apiName PostCard
        # @apiGroup Cards
        # @apiExample Example usage:
        # curl -X POST \
        # http://localhost:3000/api/v1/cards \
        # -H 'cache-control: no-cache' \
        # -H 'content-type: application/json' \
        # -d '{
        #   "number": 1111111122222222,
        #   "value": 300,
        #   "status": 1,
        #   "expired_at": "2018-07-26",
        #   "user_id": 3,
        #   "invoice_id": 0
        # }'
        # @apiParam {Number} number card number must be 16 digit.
        # @apiParam {Number} value card value.
        # @apiParam {Number} status card status.
        # @apiParam {Date} expired_at  card expired Date.
        # @apiParam {Number} user_id card user ID.
        # @apiParam {Number} invoice_id card invoice ID. 
        # @apiSuccess {Number} id card unique ID.
        # @apiSuccess {Number} number card unique number.
        # @apiSuccess {Number} value card value.
        # @apiSuccess {Number} status card status.
        # @apiSuccess {Date} expired_at  card expired Date.
        # @apiSuccess {Number} invoice_id card invoice ID.
        # @apiSuccess {Date} created_at  Date created.
        # @apiSuccess {Date} updated_at  Date Updated.
        # @apiSuccessExample Success-Response:
        # HTTP/1.1 200 OK
        #     {
        #         "id": 7,
        #         "number": 1178702457640936,
        #         "value": 500,
        #         "status": 2,
        #         "expired_at": "2022-05-20",
        #         "user_id": 1,
        #         "invoice_id": 0,
        #         "created_at": "2018-07-25T13:24:23.665Z",
        #         "updated_at": "2018-07-25T13:24:23.665Z"
        #     }
        # @apiError MissingToken missing user name or password.
        # @apiErrorExample Error-Response1:
        # HTTP/1.1 422 Missing token
        #   {
        #     "error": "Missing token"
        #   }
        # @apiError ExistingNumber card number has already been taken.
        # @apiErrorExample Error-Response2:
        # HTTP/1.1 Existing Number
        #   {
        #     "error": "has already been taken"
        #   }
        # @apiError InvalidNumber card number not equal 16 digit.
        # @apiErrorExample Error-Response3:
        # HTTP/1.1 Invalid Number
        #   {
        #     "error": "must be 16 digit long"
        #   }
        # =end

        @card = Card.new(card_params)
        respond_to do |format|
          if @card.save
            CardsLog.create(:user_id => 1,:action_type => 1,:ip => request.remote_ip,:card_id => @card.id)
            format.json { render json: @card, status: :created, location: @card }
          else
            format.json { render json: @card.errors, status: :unprocessable_entity }
          end
        end

      end

      # PATCH/PUT /cards/:id
      def update

        # =begin
        # @api {put} /api/v1/cards/{:id} 4-Update an existing Card
        # @apiVersion 0.3.0
        # @apiName PutCard
        # @apiGroup Cards
        # @apiExample Example usage:
        # curl -X PUT \
        # http://localhost:3000/api/v1/cards/6 \
        # -H 'cache-control: no-cache' \
        # -H 'content-type: application/json' \
        # -d '{
        #   "value": 400,
        #   "status": 2,
        #   "expired_at": "2018-07-26",
        #   "user_id": 3
        # }'
        # @apiParam {Number} value card value.
        # @apiParam {Number} status card status.
        # @apiParam {Date} expired_at  card expired Date.
        # @apiParam {Number} user_id card user ID. 
        # @apiSuccess {Number} id card unique ID.
        # @apiSuccess {Number} number card unique number.
        # @apiSuccess {Number} value card value.
        # @apiSuccess {Number} status card status.
        # @apiSuccess {Date} expired_at  card expired Date.
        # @apiSuccess {Number} invoice_id card invoice ID.
        # @apiSuccess {Date} created_at  Date created.
        # @apiSuccess {Date} updated_at  Date Updated.
        # @apiSuccessExample Success-Response:
        # HTTP/1.1 200 OK
        #     {
        #         "id": 6,
        #         "number": 1155463457640936,
        #         "value": 200,
        #         "status": 2,
        #         "expired_at": "2022-05-20",
        #         "user_id": 1,
        #         "invoice_id": 0,
        #         "created_at": "2018-07-25T13:24:23.665Z",
        #         "updated_at": "2018-07-25T13:24:23.665Z"
        #     }
        # @apiError MissingToken missing user name or password.
        # @apiErrorExample Error-Response1:
        # HTTP/1.1 422 Missing token
        #   {
        #     "error": "Missing token"
        #   }
        # @apiError CardNotFound The id of the Card was not found. 
        # @apiErrorExample Error-Response2:
        # HTTP/1.1 404 Not Found
        #   {
        #     "error": "CardNotFound"
        #   }
        # =end

        respond_to do |format|
          if @card.update(card_params)

            if params[:card][:status].to_i == 2
              CardsLog.create(:user_id => 1,:action_type => 2,:ip => request.remote_ip,:card_id => @card.id)
            end
            format.json { render json: @card, status: :ok, location: @card }
          else
            format.json { render json: @card.errors, status: :unprocessable_entity }
          end
        end

      end

      def cards_status

        # =begin
        # @api {get} /api/v1/cards_status?id={:id} 6-Suspend a Specific Card
        # @apiVersion 0.3.0
        # @apiName SuspendCard
        # @apiGroup Cards
        # @apiExample Example usage:
        # curl -i http://localhost:3000/api/v1/cards_status?id=22
        # @apiParam {Number} id card unique ID.
        # @apiSuccess {Number} status card status(1 for enable & 4 for suspend).
        # @apiSuccess {Number} id card unique ID.

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.erb
<%= form_with(model: card, local: true) do |form| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :value %>
    <%= form.number_field :value %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status,options_for_select([['Active',1],['Charged',2],['pending',3],['disabled',4]]),  {}, {} %>
  </div>

  <div class="field">
    <%= form.label :expired_at %>
    <%= form.date_select :expired_at %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :invoice_id %>
    <%= form.number_field :invoice_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cards/cards_status.html.erb
<%# debug(@card_status.status)%>
<%# debug(params[:id])%>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= form_with(model: @card, local: true) do |form| %>
    <% if @card.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>
  
        <ul>
        <% @card.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <p>
      <strong>Card Number:</strong>
      <%= @card.number.scan(/.{1,4}/).join('-') %>
      </p>
    </div>

    <div class="field">
    <p>
    <strong>User:</strong>
    <%= @card.user.firstname + " " + @card.user.lastname %>
    </p>
    </div>
  
    <div class="field">
      <%= form.label :value %>
      <%= form.number_field :value %>
    </div>
  
    <div class="field">
      <%= form.label :status %>
      <%= form.select :status,options_for_select([['Active',1],['Charged',2],['pending',3],['disabled',4]], :selected => @card.status),  {}, {} %>
    </div>
  
    <div class="field">
      <%= form.label :expired_at %>
      <%= form.date_select :expired_at %>
    </div>
  
    <div class="field">
      <%= form.label :invoice_id %>
      <%= form.number_field :invoice_id %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>
<h1><%= t('cards.cards') %></h1>

    <%= form_tag  url_for(:controller => 'cards', :action => 'search'), :method => 'get' do %>

        <div>
            <div>
                 <div>
                     <div >
                       <div style="width:40%; height:180px; background:#f6f2f1; box-shadow: 0 0 8px #ccc; margin-bottom:20px;">
                         <div>
                           <div>
                           <input type="text" name="search"  placeholder="Search about something" >
                           <br><br><%= t('user name') %> <input type="text" name="search_user"  placeholder="Search for a spacific user" >
                           <div  style="margin-top:20px;">
                               <%= t('card status') %>
                              <%= select_tag :status,options_for_select([['Active',1],['Charged',2],['pending',3],['disabled',4]]), {:include_blank => 'select status'} %>
                            
                              <br><h4><%= t('Expiration Date') %>:</h4>
                              <%= t('From') %> <%= date_field_tag :searchdatefrom %>
                              <%= t('To') %> <%= date_field_tag :searchdateto %>
                             </div>
                            <div style="margin-top:20px;">
                                <button type="submit" ><%= t('search') %> </button>
                            </div>
                           </div>
                         </div>
                       </div>
                     </div>
                 </div>
            </div>
        </div>
      <% end %>
<br><br>
<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Number</th>
      <th>Value</th>
      <th>Status</th>
      <th>Expired at</th>
      <th>Operation ID</th>
      <th>Invoice</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.user.firstname + " " + card.user.lastname %></td>
        <td><%= card.number.scan(/.{1,4}/).join('-') %></td>
        <td><%= card.value %></td>
        <% if card.status == 1 %>
        <td><%= "Active" %></td>
        <% elsif card.status == 2 %>
        <td><%= "Charged" %></td>
        <% elsif card.status == 3 %>
            <td><%= "pending" %></td>
        <% elsif card.status == 4 %>
            <td><%= "disabled" %></td>
        <% end %>
        <td><%= card.expired_at %></td>
        <td><%= card.operation_id %></td>
        <td><%= card.invoice_id %></td>
        <% if card.status == 4 %>
        <td><a href="/cards_status?id=<%= card.id %>" class="btn btn-primary">push to enable</a></td>
        <% else %>
        <td><a href="/cards_status?id=<%= card.id %>" class="btn btn-primary">push to disable</a></td>
        <% end %>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button><%= link_to 'New Card', new_card_path %></button>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Back', cards_path %>

app/views/cards/search.html.erb
<section >
<%= form_tag  url_for(:controller => 'cards', :action => 'search'), :method => 'get' do %>

  <div>
      <div>
           <div>
               <div >
                 <div style="width:40%; height:180px; background:#f6f2f1; box-shadow: 0 0 8px #ccc; margin-bottom:20px;">
                   <div>
                     <div>
                     <input type="text" name="search"  placeholder="Search about something" >
                     <br><br><%= t('user name') %> <input type="text" name="search_user"  placeholder="Search for a spacific user" >
                     <div  style="margin-top:20px;">
                         <%= t('card status') %>
                        <%= select_tag :status,options_for_select([['Active',1],['Charged',2],['pending',3],['disabled',4]]), {:include_blank => 'select status'} %>
                      
                        <br><h4><%= t('Expiration Date') %>:</h4>
                        <%= t('From') %> <%= date_field_tag :searchdatefrom %>
                        <%= t('To') %> <%= date_field_tag :searchdateto %>
                       </div>
                      <div style="margin-top:20px;">
                          <button type="submit" ><%= t('search') %> </button>
                      </div>
                     </div>
                   </div>
                 </div>
               </div>
           </div>
      </div>
  </div>
<% end %>
<br><br>

 <table>
  <thead>
    <tr>
       <th style="color:#363669 !important;">Username</th>
       <th style="color:#363669 !important;">Number</th>
       <th style="color:#363669 !important;">Value</th>
       <th style="color:#363669 !important;">Status</th>
       <th style="color:#363669 !important;">Expired at</th>
       <th style="color:#363669 !important;">Operation ID</th>
       <th style="color:#363669 !important;"><%= t('created at') %></th>
       <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>

    <% @Cards.each do |card| %>
   
      <tr>
        <td><%= card.user.firstname + " " + card.user.lastname %></td>
        <td><%= card.number.scan(/.{1,4}/).join('-') %></td>
        <td><%= card.value %></td>
        <% if card.status == 1 %>
        <td><%= "Active" %></td>
        <% elsif card.status == 2 %>
        <td><%= "Charged" %></td>
        <% elsif card.status == 3 %>
            <td><%= "pending" %></td>
        <% elsif card.status == 4 %>
            <td><%= "disabled" %></td>
        <% end %>
        <td><%= card.expired_at %></td>
        <td><%= card.operation_id %></td>
        <td><%= card.created_at %></td>
        <td><%= link_to 'Show', card %></td>
      </tr>
      <% end %>
  </tbody>
</table>
<br>
</section>

app/views/cards/searchpost.html.erb
<%# debug(params)%>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @card.number.scan(/.{1,4}/).join('-') %>
</p>

<p>
  <strong>Value:</strong>
  <%= @card.value %>
</p>

<p>
  <strong>Status:</strong>
  <%= @card.status %>
</p>

<p>
  <strong>Expired at:</strong>
  <%= @card.expired_at %>
</p>

<p>
  <strong>Operation Id:</strong>
  <%= @card.operation_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @card.user.firstname + " " +  @card.user.lastname   %>
</p>

<p>
  <strong>Invoice:</strong>
  <%= @card.invoice_id %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>